Updating old permissions
Basis-Theory/basistheory-integration-guides pull request #61
Opened 2021-12-29 23:32 UTC by jleon15

## Description

- https://linear.app/basis-theory/issue/ENG-1885/update-permissions-in-guides-and-sample-app

## Testing required outside of automated testing?

- [x] Not Applicable

### Screenshots (if appropriate):

- [x] Not Applicable

## Rollback / Rollforward Procedure

- [x] Roll Forward
- [ ] Roll Back

## Reviewer Checklist

- [ ] Description of Change
- [ ] Description of outside testing if applicable.
- [ ] Description of Roll Forward / Backward Procedure
- [ ] Documentation updated for Change

2021-12-30 14:50 UTC, koalaty-code requested changes

2021-12-30 14:50 UTC, koalaty-code commented on collections/guides/collect_payments/index.md
> +    To use your Stripe Reactor, you'll need a <code>server-to-server</code> application with the following permissions <code>token:pci:read:high</code>, <code>token:pci:create</code> and <code>token:
```suggestion
    To use your Stripe Reactor, you'll need a <code>server-to-server</code> application with the following permissions <code>token:pci:read:low</code>, <code>token:pci:create</code> and <code>token:pci:use:reactor</code>.
```

`token:pci:read:high` isn't an available permission without PCI attestation.

2021-12-30 14:50 UTC, koalaty-code commented on collections/guides/setup_first_reactor/setup_first_reactor.md
> +    To run a Reactor, an application needs `token:<classification>:read:<impact_level>` and `token:<classification>:use:reactor` permissions. For this example you will need `token:pci:read:<classific
```suggestion
    To run a Reactor, an application needs `token:<classification>:use:reactor` permission. For this example the application will need `token:pci:use:reactor` permission.
```

2021-12-30 14:50 UTC, koalaty-code commented on collections/guides/tokenize_customer_data_in_browser/index.md
> +    You'll need a <code>Client-side</code> [Application](https://docs.basistheory.com/api-reference/#applications) created with the <code>token:pii:create</code> permission for this step.
We also need to update the `submit()` handler example to override default Privacy Settings for `pii` classification:
```
  const token = await bt.tokens.create({
    type: 'token',
    data: {
      name,
      ssn,
      phone
    },
    privacy: {
      classification: 'pii'
    });
```

2022-01-03 19:22 UTC, dhudec submitted a review, later dismissed

2022-01-05 14:19 UTC, koalaty-code approved these changes

2022-01-05 14:28 UTC, dhudec approved these changes

2022-01-05 16:12 UTC, merged

2022-01-10 17:08 UTC, bt-platform-eng commented
:tada: This PR is included in version 1.2.0 :tada:

The release is available on [GitHub release](https://github.com/Basis-Theory/basistheory-integration-guides/releases/tag/v1.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: