ENG-1984 - create card react guide
Basis-Theory/basistheory-integration-guides pull request #66
Opened 2022-01-26 17:55 UTC by djejaquino

## Description

-

## Testing required outside of automated testing?

- [ ] Not Applicable

### Screenshots (if appropriate):

![localhost_4001_guides_collect-atomic-cards-with-elements-react_](https://user-images.githubusercontent.com/5549408/151219248-6f8d6527-ab4b-4a86-b9fa-473591766eda.png)

## Rollback / Rollforward Procedure

- [ ] Roll Forward
- [ ] Roll Back

## Reviewer Checklist

- [ ] Description of Change
- [ ] Description of outside testing if applicable.
- [ ] Description of Roll Forward / Backward Procedure
- [ ] Documentation updated for Change

2022-01-27 19:26 UTC, lcschy commented on collections/guides/collect_pii_react/index.md
> +- Disable the both inputs and "Submit" `button` during the tokenization request inside the `submit` function;
Disable both inputs and the "Submit" button

2022-01-27 19:29 UTC, lcschy commented on collections/guides/collect_cards_react/index.md
> +- Disable the `CardElement` and "Submit" `button` during the tokenization request inside the `submit` function;
and **the** "Submit" button

2022-01-27 19:29 UTC, lcschy commented on collections/guides/collect_cards_react/index.md
> +The created token in `submit` function can be used in a variety of ways:
in **the** submit

2022-01-27 19:30 UTC, lcschy requested changes
Just a couple of grammar comments. Content looks good.

2022-01-28 03:03 UTC, armsteadj1 requested changes
Updated quite a few of the paragraphs and moved a few things around. Let me know if you think i moved too many thing. 🤣

2022-01-28 03:03 UTC, armsteadj1 commented on collections/guides/collect_pii_react/index.md
> +
```suggestion
Success! 🎉, your application is now collecting and storing credit cards in Basis Theory platform. The example above uses a few of the [Element's user experience](https://docs.basistheory.com/elements/#introduction) features to ensure the best experience to your customers:

- Pass a `mask` to the `ssn` field, restricting user input to digits only and formatting the output;
- Use a `transform` option in the `ssn` field to strip out dash '-' characters from the tokenized data;
- Disable the "Submit" `<button>` while the `fullName` field is empty or the `ssn` field is not `complete`, by listening to their `onChange` event;
- Disable the both inputs and the "Submit" `button` during the tokenization request inside the `submit` function;
- Display the full `tokens` response;
- Log any tokenization errors to the `console`;

```

2022-01-28 03:03 UTC, armsteadj1 commented on collections/guides/collect_pii_react/index.md
> +- Log any tokenization errors to the `console`;
```suggestion

```
moved up

2022-01-28 12:02 UTC, djejaquino commented on collections/guides/collect_cards_react/index.md
> +If you'd like to follow along with this guide from scratch, we suggest creating a new React sandbox using <a href="http://codesandbox.io/">codesandbox.io</a> and getting started from there! Want to j
Yes, but this is consistent across other examples. I would probably let this be reviewed/decided in that Guides task next cycle. What do you think?

2022-01-28 12:17 UTC, djejaquino commented on collections/guides/collect_cards_react/index.md
> +- Log any tokenization errors to the `console`;
That's the thing. We don't. In the guide we do the very minimal to integrate. The live example that they can explore has those things. I am going to use your verbiage but stick with the same spot.

2022-01-28 12:34 UTC, lcschy approved these changes

2022-01-28 14:14 UTC, armsteadj1 approved these changes

2022-01-28 14:14 UTC, armsteadj1 commented on collections/guides/collect_cards_react/index.md
> +If you'd like to follow along with this guide from scratch, we suggest creating a new React sandbox using <a href="http://codesandbox.io/">codesandbox.io</a> and getting started from there! Want to j
sounds good to me!

2022-01-28 14:18 UTC, merged

2022-01-28 14:19 UTC, bt-platform-eng commented
:tada: This PR is included in version 1.3.0 :tada:

The release is available on [GitHub release](https://github.com/Basis-Theory/basistheory-integration-guides/releases/tag/v1.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: