ENG-2185: home page redesign and quickstarts landing page
Basis-Theory/basistheory-integration-guides pull request #78
Opened 2022-02-11 23:46 UTC by brigonzalez

## Description

- home page redesign and quickstarts landing page

## Testing required outside of automated testing?

- [x] Not Applicable

### Screenshots (if appropriate):
<img width="1908" alt="Screen Shot 2022-02-11 at 4 26 01 PM" src="https://user-images.githubusercontent.com/11567066/153684100-70791731-3b76-4206-8b5a-d378542aa33a.png">

## Rollback / Rollforward Procedure

- [x] Roll Forward
- [ ] Roll Back

## Reviewer Checklist

- [ ] Description of Change
- [ ] Description of outside testing if applicable.
- [ ] Description of Roll Forward / Backward Procedure
- [ ] Documentation updated for Change

2022-02-12 00:12 UTC, brigonzalez commented
getting a weird issue where the icons aren't appearing on the quickstart home page. wondering if this is just a me problem or if others can reproduce this issue

2022-02-14 19:25 UTC, armsteadj1 approved these changes

2022-02-14 19:34 UTC, armsteadj1 requested changes

2022-02-14 19:34 UTC, armsteadj1 commented on index.markdown
> +                <div class="quickstart-subtitle">Learn how to use Basis Theory use tokenization to encrypt personal information and safely share it to Auth0.</div>
```suggestion
                <div class="quickstart-subtitle">Get a foundational understanding of how to secure your data with Basis Theory allowing you to no longer worry about the underlying storage or encryption of the data.</div>
```

2022-02-14 19:34 UTC, armsteadj1 commented on index.markdown
> +                <div>Where your Tokens and Applications are defined, managed, and stored.</div>
```suggestion
                <div>Tenats are where Tokens and Applications are defined, managed, and stored.</div>
```

2022-02-14 19:34 UTC, armsteadj1 commented on index.markdown
> +                <div>Send tokenized data without touching it.</div>
```suggestion
                <div>Proxy enables making HTTP requests containing sensitive tokenized data to your 3rd party partners, without your systems needing access to the raw data.</div>
```

2022-02-14 19:52 UTC, armsteadj1 approved these changes

2022-02-14 20:16 UTC, merged

2022-02-16 21:01 UTC, bt-platform-eng commented
:tada: This PR is included in version 1.4.0 :tada:

The release is available on [GitHub release](https://github.com/Basis-Theory/basistheory-integration-guides/releases/tag/v1.4.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: